### ISSUE TITLE
Move docs to https://testing-library.com/puppeteer?

### ISSUE THREAD

**Issue by kentcdodds** [patrickhulce/pptr-testing-library#9]
Hey @patrickhulce! Would you be interested in moving your docs to https://testing-library.com/puppeteer? (Similar to https://testing-library.com/react and https://testing-library.com/cypress)

The site source is here: https://github.com/alexkrolick/testing-library-docs

I think it'd be pretty trivial to move things over.

What do you think? cc @alexkrolick

**Comment by patrickhulce** [comment]
Yeah SGTM! I'll try to put together something this weekend.

**Comment by patrickhulce** [comment]
well "this weekend" turned into 6 weeks later 😆 but PR is up finally!

**Comment by kentcdodds** [comment]
Merged! Here it is: https://testing-library.com/pptr
